### ISSUE TITLE
Insta and email logo in footer

### ISSUE THREAD

**Issue by SachinSahu431** [Literary-IITT/lac-hugo-website#5]
Can we do something for this img src so that we need not use exact URL?  
https://github.com/Literary-IITT/Literary-IITT.github.io/blob/4e81c75a46206c5bb42777cc0670204d407b01f2/themes/kross/layouts/partials/footer.html#L44
https://github.com/Literary-IITT/Literary-IITT.github.io/blob/4e81c75a46206c5bb42777cc0670204d407b01f2/themes/kross/layouts/partials/footer.html#L45

**Comment by NobleMathews** [comment]
Check the current src, don't hard set the URL for such static components
